main:
	gcc -o obj/main test/main.c
	./obj/main data/big_random1.txt data/big_random2.txt data/big_random3.txt

hm:
	gcc -o obj/hm_test test/hashmap_test.c
	./obj/hm_test

list:
	gcc -o obj/list_test test/list_test.c
	./obj/list_test

clean:
	rm -f obj/main obj/hm_test obj/list_test
